#!/bin/bash


## Note that this file only solves the issue with $ $ to \\( \\) (escape the \ in markdown)
##   and please don't use begin aligned with \\. jekyll will interpret in a weird way.

# So this file is only for a minimal usage: convert some posts' latex code to markdown.
#   Then jekyll interpret the markdown...

file=$1
./debuck $file
perl -i -pe 's/\\\(/\\\\\(/g; s/\\\)/\\\\\)/g; s/\\\[/\\\\\[/g; s/\\\]/\\\\\]/g;' $file
