#!/bin/bash


## Note that this file only solves the issue with $ $ to \\( \\) (escape the \ in markdown)
##   and please don't use begin aligned with \\. jekyll will interpret in a weird way.

# So this file is only for a minimal usage: convert the html files if needed.
#  Should not call it in gen, since it will overwrite music 270.
#   therefore no need to perform the last conversion

file=$1
./debuck $file
# later: change <em> </em> to _ ... werid generate md.
# also, avoid the usage of {{ }}, which are liquid variables. Maybe change {{ to { {, so does }
#perl -i -pe 's/\\\(/\\\\\(/g; s/\\\)/\\\\\)/g; s/\\\[/\\\\\[/g; s/\\\]/\\\\\]/g;' $file
